# Generated by Django 5.0.6 on 2024-05-14 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(blank=True, max_length=50, null=True, verbose_name='Nombre')),
                ('precio', models.IntegerField(verbose_name='Precio')),
            ],
        ),
        migrations.CreateModel(
            name='Equipaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.IntegerField(verbose_name='Marca')),
                ('numero_objeto', models.IntegerField(verbose_name='Numero de objetos')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True, max_length=50, null=True, verbose_name='Nombre')),
                ('apellido', models.TextField(blank=True, max_length=50, null=True, verbose_name='Apellido')),
                ('id_boleto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='GrapheneRealTime.boleto')),
                ('id_equipaje', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='GrapheneRealTime.equipaje')),
            ],
        ),
    ]
