# Generated by Django 5.0.6 on 2024-05-14 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrapheneRealTime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipaje',
            name='marca',
            field=models.TextField(verbose_name='Marca'),
        ),
    ]
