# Generated by Django 5.0.6 on 2024-05-14 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrapheneRealTime', '0002_alter_equipaje_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='id_boleto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GrapheneRealTime.boleto'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='id_equipaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GrapheneRealTime.equipaje'),
        ),
    ]
